version: "3.7"
services:
  authz:
    build:
      context: ./authz
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000

  service:
    build:
      context: ./service
      dockerfile: Dockerfile

  envoy:
    image: envoyproxy/envoy-dev
    volumes: 
      - ./envoy-config.yaml:/envoy-config.yaml
      - ./crt.pem:/crt.pem
      - ./key.pem:/key.pem
    command:
      - -c envoy-config.yaml
    ports:
      - 8000:8000
      - 9901:9901